version: '3.8'

services:
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    restart: unless-stopped
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home
    hostname: docker

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    restart: unless-stopped
    privileged: true
    depends_on:
      - dind
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-client:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
  docker-certs-ca:
  docker-certs-client:
