version: '3.8'
services:
  dind:
    image: docker:dind
    privileged: true
    container_name: project2-compose_dind_1
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: project2-compose_jenkins_1
    user: root
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_TLS_VERIFY=0
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    command: >
      /bin/sh -c "echo 'Starting Jenkins...' && /usr/local/bin/jenkins.sh"

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
  docker-certs-ca:
  docker-certs-client: